// The organisation whose map is open.
//
// The app shows one organisation at a time (BCSIR, Taqwa Fabrics, ...). Each has
// its own folders:
//   public/data/<id>/     datasets, org.json and one folder per building with floors
//   public/models/<id>/   GLB models
//   public/image/<id>/    photos and the logo
// boot.js picks the organisation (URL or the picker), loads its index
// (data/<id>/index.json, generated by scripts/lib/catalog.mjs) and calls
// setActiveOrg() BEFORE the map modules are imported, so they can read it while
// they load.
import { encodeAssetPath, orgAssetKey, orgAssetPath } from "./asset-paths.js";

let active = null;

export function setActiveOrg(index) { active = index || null; }
export const activeOrg = () => active;
export const orgId = () => active?.id ?? null;

// Path in public/ of a file in the organisation's data folder.
export const orgDataPath = (file) => `data/${active?.id}/${String(file).replace(/^\/+/, "")}`;

// Path in public/ of a dataset ("buildings", "roads", ...), or null when the
// organisation has no such file.
export function datasetPath(key) {
  const file = active?.datasets?.[key];
  return file ? orgDataPath(file) : null;
}
export const datasetFile = (key) => active?.datasets?.[key] || null;

// Dataset key of a published data path ("data/bcsir/Pathway.geojson"), or null.
export function datasetKeyOfPath(published) {
  for (const key of Object.keys(active?.datasets || {})) if (datasetPath(key) === published) return key;
  return null;
}

export const modelPath = (value) => orgAssetPath("models", value, active?.id);
export const modelKey = (value) => orgAssetKey("models", value, active?.id);
export const imagePath = (value) => orgAssetPath("image", value, active?.id);
export const imageKey = (value) => orgAssetKey("image", value, active?.id);

// Preference key in localStorage, kept apart per organisation.
export const storageKey = (name) => `indoor-map:${active?.id || "none"}:${name}`;

export { encodeAssetPath };
